### ISSUE TITLE
Finale seems incorrect (not sure about the others)

### ISSUE THREAD

**Issue by gcherreralim** [bradlindblad/schrute#12]
Hi, I haven't gotten around to looking through all the episodes, but I went through the last episode and it seems jumbled up and/or incomplete. Not sure if it's just jumbled up or both. The last line in the data cuts off with Jim and Pam's conversation with Dwight about leaving Dunder Mifflin.

**Comment by bradlindblad** [comment]
Hey thanks for the issue. You're right, it looks like my source jumbled up the order of some of the lines, but all the lines appear to be there. 

I found the last line of the series: 

> Pam: I thought it was weird when you picked us to make a documentary. But all in all...I think an ordinary paper company like Dunder Mifflin was a great subject for a documentary. There's a lot of beauty in ordinary things. Isn't that kind of the point?  


at this location:
`schrute::theoffice %>% dplyr::filter(index == 54710)
`
If you want to submit a PR to order these records, feel free. Thanks!
