### ISSUE TITLE
Missing data for some episodes

### ISSUE THREAD

**Issue by yaylinda** [bradlindblad/schrute#13]
Hi! I just came across this package and have been using it in R. Thanks for curating this!

However, it seems like the dataset is missing data for some episodes? 

For example: Season 3, Episode 11
```
subset(theoffice, theoffice$season == 3 & theoffice$episode == 11)
```
returns a tibble of 0x12 

Same for these other episodes:
- S4 E2
- S4 E4
- S4 E6
- S4 E8
- S5 E2
- S5 E15
- S6 E5
- S6 E18
- S7 E12
- S9 E23

**Comment by bradlindblad** [comment]
Looks like this happened in my script when there was a 2-part episode. I'll make some time to modify the python scraping script to re-capture the data. Thanks for creating the issue

**Comment by yaylinda** [comment]
Awesome, thank you so much!

**Comment by bradlindblad** [comment]
@yaylinda Just looking at this now. It looks like all of the instances you cite above were 2-part episodes. In the source that I scraped, both parts were on the same html page. Long story short, all the text from those episodes are there, but the **episode**  field skips counting the 2nd in the 2-part series.
