### ISSUE TITLE
Add Directors and Writers?

### ISSUE THREAD

**Issue by hypercompetent** [bradlindblad/schrute#3]
Hi Brad,

Thanks for assembling this really fun dataset! Something I was curious about after exploring the data in the schrute R package was how directors and writers contribute to the similarities or differences in word use per episode.

So, I went through IMDB and grabbed the credited directors and writers there for each episode [in this Gist: office_writers.csv](https://gist.github.com/hypercompetent/222ec32cfb9dfcc9c045a803e50f2a41). Where there are multiple people credited, they're semicolon separated within the associated column. 

I'll leave it up to you to determine if/how you'd like to incorporate these additional columns into your data structure.

Cheers,
-Lucas

**Comment by bradlindblad** [comment]
Hey glad you like the package and yes, I'd love to include that!
If you want to submit a PR that would be great, if not, I can incorporate the changes directly.
Thanks! @hypercompetent
