### ISSUE TITLE
air_date (and imdb_rating) information appears incorrect

### ISSUE THREAD

**Issue by skent259** [bradlindblad/schrute#9]
Hi, 

I noticed that some of the air_date and imdb_rating information from `theoffice` data set in this package is incorrect.  Just downloaded version 0.2.0 from CRAN, and was digging in.  

You can see this clearly from Season 4, but it occurs elsewhere. For example, S4 E03 says it was published on October 11:

```{r}
theoffice %>% 
  filter(season == "04", episode == "03") %>%
  select(season, episode, episode_name, air_date, imdb_rating) %>%
  unique()

## # A tibble: 1 x 5
##   season episode episode_name                        air_date   imdb_rating
##   <chr>  <chr>   <chr>                               <fct>            <dbl>
## 1 04     03      Dunder Mifflin Infinity (Parts 1&2) 2007-10-11         8.5
```

But IMDB reports a publish date of October 4 (https://www.imdb.com/title/tt0386676/episodes?season=4).

I think the issue is that multi-part episodes increment the episode count by 2 in this dataset, whereas pulling the IMDB data directly would only increment the episode count by 1.  This creates a miss-match on the join and would also explain the many office episodes with NA at the end of the season.  

I found a (fairly manual) way to correct this that I'm willing to share if needed.  I also have a 'corrected' version of the data at https://github.com/skent259/tidy-tuesday/blob/master/2020/2020-03-17/theoffice-data.rds.  Note this is my first GitHub issue, so I'm not sure the best way to help with this.  Please let me know if you need more information.

**Comment by bradlindblad** [comment]
Great catch @skent259 ! I’m away from a computer for a few days, so I’ll have to update it at that point, unless you want to make a pull request? Totally fine if you don’t!

**Comment by bradlindblad** [comment]
I'm not seeing the same errors as you. On the imdb page for season 4, episode 3, I see an original air date of October 11, 2020, not October 4.

**Comment by skent259** [comment]
Episode 3 does have an air date of October 11, but the episode "Dunder Mifflin Infinity (Parts 1 & 2)" is actually the second 'episode' of the season, and aired on October 4.  The number of episodes in IMDB vs the data from this package is what I believe is the source of the issue.
